version: "3.8"

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    restart: on-failure
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app_network
    volumes:
      - ./logs:/app/logs

volumes:
  postgres-volume:
    driver: local

networks:
  app_network:
    driver: bridge
