name: Deploy to GCP

on:
    push:
        branches:
            - main

# REQUIRED: Allow workflow to request OIDC token
permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - id: "auth"
              name: "Authenticate to Google Cloud"
              uses: "google-github-actions/auth@v2"
              with:
                  workload_identity_provider: "projects/PR967610729806/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
                  service_account: "github-actions-sa@product-spring-boot.iam.gserviceaccount.com"

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v2"

            - name: "Use gcloud CLI"
              run: |
                  gcloud info
                  gcloud projects list
